add function to compute custom name for errors plugin generated types
hayes/pothos pull request #702
Opened 2022-12-09 23:16 UTC by TheMightyPenguin

# Description

Adds an option for the `@pothos/plugin-errors` plugin to customize how type names are generated. 

Resolves https://github.com/hayes/pothos/issues/566

2022-12-09 23:16 UTC, TheMightyPenguin commented
@hayes let me know what you think of the approach, once we are ok with the general approach I can also add a similar option for the `with-input` plugin!

2022-12-10 00:50 UTC, hayes requested changes
Overall, this is awesome.

I think what I would change is how where in the builder options the type-name function is defined.

For consistency, I think what I would like to do is add this function to the default*TypeOptions fields:


```typescript
export const builderWithCustomErrorTypeNames = new SchemaBuilder<{}>({
  plugins: [ErrorPlugin, ValidationPlugin],
  errorOptions: {
    defaultTypes: [Error],
    defaultUnionOptions: {
        name: ({ fieldName, parentTypeName }) => `${fieldName}Result`
    },
    defaultResultOptions: {
        name: ({ fieldName, parentTypeName }) => `${fieldName}Success`
    },
  },
});
```

Any type that gets automatically generated (and has an automatically assigned name) in a pothos plugin should have a place in the builder options to define default options.  This is already required for interoperability between plugins, which should make this easy to extend to other plugins as well in a consistent way.

2022-12-10 00:50 UTC, hayes commented on .changeset/slow-tigers-fail.md
> +'@pothos/plugin-errors': patch
This is probably one on the most detailed and useful changesets to date!

This change should probably be a minor though, as it's adding a new feature

2022-12-10 00:50 UTC, hayes commented on packages/plugin-errors/tests/index.test.ts
> +    expect(printSchema(schema)).toMatchSnapshot();
thanks for updating test, I like the approach of wrapping the schema building logic in a function so you can build with different option!

2023-01-06 23:37 UTC, hayes commented on packages/plugin-errors/README.md
> +            name: ({ parentTypeName, fieldName }) => `${fieldName}_Custom`,
might be worth no using exactly the same name in the docs for both union and result (because this would cause a collision)

2023-01-06 23:38 UTC, hayes approved these changes
Looks great to me, thanks for adding this ❤️

2023-01-07 00:54 UTC, hayes commented on packages/plugin-errors/README.md
> +            name: ({ parentTypeName, fieldName }) => `${fieldName}_Custom`,
```suggestion
            name: ({ parentTypeName, fieldName }) => `${fieldName}_CustomResult`,
```

2023-01-07 00:54 UTC, hayes commented on packages/plugin-errors/README.md
> +            name: ({ parentTypeName, fieldName }) => `${fieldName}_Custom`,
```suggestion
            name: ({ parentTypeName, fieldName }) => `${fieldName}_CustomUnion`,
```

2023-01-07 00:55 UTC, hayes commented on .changeset/slow-tigers-fail.md
> +      name: ({ parentTypeName, fieldName }) => `${fieldName}_Custom`,
```suggestion
            name: ({ parentTypeName, fieldName }) => `${fieldName}_CustomResult`,
```

2023-01-07 00:55 UTC, hayes commented on .changeset/slow-tigers-fail.md
> +      name: ({ parentTypeName, fieldName }) => `${fieldName}_Custom`,
```suggestion
            name: ({ parentTypeName, fieldName }) => `${fieldName}_CustomUnion`,
```

2023-01-07 00:59 UTC, hayes commented
looks like type-checking the test server fails, I think it's failing to import the schema after it was refactored

2023-01-07 02:24 UTC, merged